# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3c < Formula
  desc "Local k3s clusters on Apple container — like k3d, without Docker"
  homepage "https://github.com/philipparndt/k3c"
  version "0.2.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/philipparndt/k3c/releases/download/v0.2.1/k3c_darwin_x86_64.tar.gz"
    sha256 "67cc33a7fa8e581d0114b03e253eacb255ad35f5b596b84a16d80c530068c059"

    define_method(:install) do
      bin.install "k3c"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/philipparndt/k3c/releases/download/v0.2.1/k3c_darwin_arm64.tar.gz"
    sha256 "f305ae03beda583c4123d21e60f65edb29e39c003bd3dd6ef98b86646adb1b47"

    define_method(:install) do
      bin.install "k3c"
    end
  end
end
