# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3c < Formula
  desc "Local k3s clusters on Apple container — like k3d, without Docker"
  homepage "https://github.com/philipparndt/k3c"
  version "0.3.1"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/philipparndt/k3c/releases/download/v0.3.1/k3c_darwin_x86_64.tar.gz"
    sha256 "b0e6f85807fd508243c50585e66ca50a8d01ff47eafe1dd98c92414f8cacfa52"

    define_method(:install) do
      bin.install "k3c"

      begin
        bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/k3c completion bash")
        (bash_completion/"k3c").write bash_output
      rescue => e
        opoo "Failed to install bash completion: #{e}"
      end

      begin
        zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/k3c completion zsh")
        (zsh_completion/"_k3c").write zsh_output
      rescue => e
        opoo "Failed to install zsh completion: #{e}"
      end

      begin
        fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/k3c completion fish")
        (fish_completion/"k3c.fish").write fish_output
      rescue => e
        opoo "Failed to install fish completion: #{e}"
      end
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/philipparndt/k3c/releases/download/v0.3.1/k3c_darwin_arm64.tar.gz"
    sha256 "cd9b74404ee5865f64e0bce16bb8829ff85db4bda7f5bf6ab70a137aabf6a8bb"

    define_method(:install) do
      bin.install "k3c"

      begin
        bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/k3c completion bash")
        (bash_completion/"k3c").write bash_output
      rescue => e
        opoo "Failed to install bash completion: #{e}"
      end

      begin
        zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/k3c completion zsh")
        (zsh_completion/"_k3c").write zsh_output
      rescue => e
        opoo "Failed to install zsh completion: #{e}"
      end

      begin
        fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/k3c completion fish")
        (fish_completion/"k3c.fish").write fish_output
      rescue => e
        opoo "Failed to install fish completion: #{e}"
      end
    end
  end
end
